---
services:
  ts-calibre-web-automated:
    extends:
      file: ../tailscale-sidecar.yml
      service: tailscale-sidecar
    container_name: ts-calibre-web-automated
    hostname: calibre
    volumes:
      - ${CONFIG_ROOT}/ts-calibre-web-automated/state:/var/lib/tailscale
      - ./ts-calibre-web-automated-config:/config

  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    network_mode: service:ts-calibre-web-automated
    depends_on:
      ts-calibre-web-automated:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      # Hardcover API Key required for Hardcover as a Metadata Provider, get one here: https://docs.hardcover.app/api/getting-started/
      - HARDCOVER_TOKEN=${HARDCOVER_API_KEY}
      - NETWORK_SHARE_MODE=false
    volumes:
      # CW users migrating should stop their existing CW instance, make a copy of the config folder, and bind that here to carry over all of their user settings etc.
      - ${CONFIG_ROOT}/Calibre-Web-Automated/Config:/config
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - ${CONFIG_ROOT}/Calibre-Web-Automated/BookIngest:/cwa-book-ingest
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - ${MEDIA_ROOT}/books:/calibre-library
      # If you use calibre plugins, you can bind your plugins folder here to have CWA attempt to add them to it's workflow (WIP)
      # If you are starting with a fresh install, you also need to copy customize.py.json to the Calibre config volume above, in /path/to/config/folder/.config/calibre/customize.py.json, see the README for more info
      - ${CONFIG_ROOT}/Calibre-Web-Automated/Plugins:/config/.config/calibre/plugins
    restart: unless-stopped
