services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_ROOT}/Bazarr/Config:/config
      - ${MEDIA_ROOT}/movies:/data/movies # should match radarr movies directory
      - ${MEDIA_ROOT}/tvshows:/data/tvshows # should match sonarr tv shows directory
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - arrs
