services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qbittorrent web interface
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
    volumes:
      - ${CONFIG_ROOT}/Gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      - TZ=America/Chicago
      - UPDATER_PERIOD=24h
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24,10.0.0.0/16
      - DNS_UPSTREAM_RESOLVERS=cloudflare,google
      - PUBLICIP_API=ip2location
      ### Wireguard Settings
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WG_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      - DNS_ADDRESS=10.2.0.1
      - LOG_LEVEL=info
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={"auth":"apikey","apikey":"${GLUETUN_API_KEY}"}
    restart: unless-stopped
