services:
  gluetun-qbittorrent-port-manager:
    image: mjmeli/qbittorrent-port-forward-gluetun-server
    restart: unless-stopped
    container_name: gt-port-manager
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - QBT_USERNAME=${QBITTORRENT_USER}
      - QBT_PASSWORD=${QBITTORRENT_PASS}
      - QBT_ADDR=http://localhost:8080
      - GTN_ADDR=http://localhost:8000
      - GTN_APIKEY=${GLUETUN_API_KEY}
