services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_ROOT}/Radarr/Config:/config
      - ${MEDIA_ROOT}/movies:/data/movies
      - ${DOWNLOADS_ROOT}:/data/downloads
      - ${CONFIG_ROOT}/Radarr/Backup:/data/Backup
    restart: unless-stopped
    network_mode: service:ts-remote-access
    depends_on:
      ts-remote-access:
        condition: service_healthy
