services:
  ts-remote-access:
    image: tailscale/tailscale:latest
    container_name: ts-remote-access
    hostname: ${TS_HOSTNAME}
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_ENABLE_HEALTH_CHECK=true
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ts-remote-access-state:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    ports:
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9002/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  ts-remote-access-state:
