services:
  ts-radarr:
    extends:
      file: ../tailscale-sidecar.yml
      service: tailscale-sidecar
    container_name: ts-radarr
    hostname: radarr
    volumes:
      - ${CONFIG_ROOT}/ts-radarr/state:/var/lib/tailscale
      - ./ts-radarr-config:/config

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ${CONFIG_ROOT}/Radarr/Config:/config
      - ${MEDIA_ROOT}/movies:/data/movies
      - ${DOWNLOADS_ROOT}:/data/downloads
      - ${CONFIG_ROOT}/Radarr/Backup:/data/Backup
    restart: unless-stopped
    network_mode: service:ts-radarr
    depends_on:
      ts-radarr:
        condition: service_healthy
